# Generated by Django 2.1.3 on 2018-11-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Start')),
                ('date_end', models.DateTimeField(verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name fo the program', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FU', 'Futebol'), ('NO', 'Novela'), ('MU', 'Musical'), ('EN', 'Entrevistas')], max_length=2)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Appointment')),
            ],
        ),
    ]
